package dandustry.recipe;

import static dandustry.item.DDMaterials.*;
import static gregtech.api.recipes.RecipeMaps.MIXER_RECIPES;
import static gregtech.api.unification.material.Materials.*;
import static gregtech.api.unification.ore.OrePrefix.dust;

public class PeriodiciumChain {
        public static void init() {
            MIXER_RECIPES.recipeBuilder().duration(270).EUt(250000)
                    .input(dust, Ruthenium)
                    .input(dust, Rhodium)
                    .input(dust, Palladium)
                    .input(dust, Silver)
                    .input(dust, Rhenium)
                    .input(dust, Osmium)
                    .input(dust, Iridium)
                    .input(dust, Platinum)
                    .input(dust, Gold)
                    .output(dust, PreciousMetals)
                    .buildAndRegister();

            MIXER_RECIPES.recipeBuilder().duration(210).EUt(250000)
                    .input(dust, Zirconium)
                    .input(dust, Hafnium)
                    .input(dust, Niobium)
                    .input(dust, Tantalum)
                    .input(dust, Molybdenum)
                    .input(dust, Tungsten)
                    .input(dust, Technetium)
                    .output(dust, RefractoryMetals)
                    .buildAndRegister();

            MIXER_RECIPES.recipeBuilder().duration(240).EUt(250000)
                    .input(dust, Titanium)
                    .input(dust, Vanadium)
                    .input(dust, Manganese)
                    .input(dust, Chrome)
                    .input(dust, Iron)
                    .input(dust, Nickel)
                    .input(dust, Cobalt)
                    .input(dust, Copper)
                    .output(dust, LightTransitionMetals)
                    .buildAndRegister();

            MIXER_RECIPES.recipeBuilder().duration(420).EUt(250000)
                    .input(dust, Beryllium)
                    .input(dust, Magnesium)
                    .input(dust, Calcium)
                    .input(dust, Strontium)
                    .input(dust, Barium)
                    .input(dust, Radium)
                    .input(dust, Scandium)
                    .input(dust, Yttrium)
                    .fluidInputs(Lithium.getFluid(144))
                    .fluidInputs(Sodium.getFluid(144))
                    .fluidInputs(Potassium.getFluid(144))
                    .fluidInputs(Rubidium.getFluid(144))
                    .fluidInputs(Caesium.getFluid(144))
                    .fluidInputs(Francium.getFluid(144))
                    .output(dust, Alkalis)
                    .buildAndRegister();

            MIXER_RECIPES.recipeBuilder().duration(420).EUt(250000)
                    .input(dust, Zinc)
                    .input(dust, Cadmium)
                    .input(dust, Aluminum)
                    .input(dust, Silicon)
                    .input(dust, Germanium)
                    .input(dust, Antimony)
                    .input(dust, Thallium)
                    .input(dust, Lead)
                    .fluidInputs(Mercury.getFluid(144))
                    .fluidInputs(Tin.getFluid(144))
                    .fluidInputs(Gallium.getFluid(144))
                    .fluidInputs(Indium.getFluid(144))
                    .fluidInputs(Bismuth.getFluid(144))
                    .fluidInputs(Polonium.getFluid(144))
                    .output(dust, PostTransitionMetals)
                    .buildAndRegister();

            MIXER_RECIPES.recipeBuilder().duration(450).EUt(250000)
                    .input(dust, Samarium)
                    .input(dust, Gadolinium)
                    .input(dust, Terbium)
                    .input(dust, Thulium)
                    .input(dust, Holmium)
                    .input(dust, Lutetium)
                    .input(dust, Promethium)
                    .input(dust, Erbium)
                    .input(dust, Dysprosium)
                    .fluidInputs(Lanthanum.getFluid(144))
                    .fluidInputs(Cerium.getFluid(144))
                    .fluidInputs(Praseodymium.getFluid(144))
                    .fluidInputs(Neodymium.getFluid(144))
                    .fluidInputs(Europium.getFluid(144))
                    .fluidInputs(Ytterbium.getFluid(144))
                    .output(dust, Lanthanoids)
                    .buildAndRegister();

            MIXER_RECIPES.recipeBuilder().duration(390).EUt(250000)
                    .input(dust, Actinium)
                    .input(dust, Thorium)
                    .input(dust, Protactinium)
                    .input(dust, Uranium235)
                    .input(dust, Americium)
                    .input(dust, Curium)
                    .input(dust, Berkelium)
                    .input(dust, Fermium)
                    .input(dust, Californium)
                    .fluidInputs(Neptunium.getFluid(144))
                    .fluidInputs(Plutonium241.getFluid(144))
                    .fluidInputs(Mendelevium.getFluid(144))
                    .fluidInputs(Einsteinium.getFluid(144))
                    .output(dust, Actinoids)
                    .buildAndRegister();

            MIXER_RECIPES.recipeBuilder().duration(450).EUt(250000)
                    .input(dust, Boron)
                    .input(dust, Carbon)
                    .input(dust, Phosphorus)
                    .input(dust, Sulfur)
                    .input(dust, Arsenic)
                    .input(dust, Selenium)
                    .input(dust, Tellurium)
                    .input(dust, Iodine)
                    .input(dust, Astatine)
                    .fluidInputs(Oxygen.getFluid(1000))
                    .fluidInputs(Nitrogen.getFluid(1000))
                    .fluidInputs(Hydrogen.getFluid(1000))
                    .fluidInputs(Fluorine.getFluid(1000))
                    .fluidInputs(Chlorine.getFluid(1000))
                    .fluidInputs(Bromine.getFluid(1000))
                    .output(dust, NonMetals)
                    .buildAndRegister();

            MIXER_RECIPES.recipeBuilder().duration(180).EUt(250000)
                    .fluidInputs(Helium.getFluid(1000))
                    .fluidInputs(Neon.getFluid(1000))
                    .fluidInputs(Argon.getFluid(1000))
                    .fluidInputs(Krypton.getFluid(1000))
                    .fluidInputs(Xenon.getFluid(1000))
                    .fluidInputs(Radon.getFluid(1000))
                    .output(dust, NobleGases)
                    .buildAndRegister();

            MIXER_RECIPES.recipeBuilder().duration(180).EUt(250000)
                    .input(dust, Nobelium)
                    .input(dust, Lawrencium)
                    .input(dust, Rutherfordium)
                    .input(dust, Dubnium)
                    .input(dust, Seaborgium)
                    .input(dust, Bohrium)
                    .input(dust, Hassium)
                    .input(dust, Meitnerium)
                    .output(dust, SuperheavyLAlloy)
                    .buildAndRegister();

            MIXER_RECIPES.recipeBuilder().duration(180).EUt(250000)
                    .input(dust, Darmstadtium)
                    .input(dust, Roentgenium)
                    .input(dust, Copernicium)
                    .input(dust, Nihonium)
                    .input(dust, Flerovium)
                    .input(dust, Moscovium)
                    .input(dust, Livermorium)
                    .input(dust, Tennessine)
                    .input(dust, Oganesson)
                    .output(dust, SuperheavyHAlloy)
                    .buildAndRegister();

            MIXER_RECIPES.recipeBuilder().duration(360).EUt(5400000)
                    .input(dust, Alkalis)
                    .input(dust, RefractoryMetals)
                    .input(dust, LightTransitionMetals)
                    .input(dust, PreciousMetals)
                    .input(dust, PostTransitionMetals)
                    .input(dust, Lanthanoids)
                    .input(dust, Actinoids)
                    .input(dust, SuperheavyLAlloy)
                    .input(dust, SuperheavyHAlloy)
                    .fluidInputs(NonMetals.getFluid(144), NobleGases.getFluid(144))
                    .output(dust, Periodicium)
                    .buildAndRegister();
        }
}